### ISSUE TITLE
Causes a crash on launch while using a modpack and forge v31.2.9

### ISSUE THREAD

**Issue by exyleknight** [MinerArcana/Astral#101]
While the description doesn't say anything specifying the cause (though I don't know anything). The mod list says it was Astral that caused an error (it's around the 33rd down the list).

```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/18/20 6:23 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at enemeez.simplefarming.client.LeavesColors.leavesColors(LeavesColors.java:18) ~[?:1.15.2-1.3.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_1397_LeavesColors_leavesColors_Block.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$9676/1059143319.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.9.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$468/2103877926.call(Unknown Source) [forge-1.15.2-31.2.9.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at enemeez.simplefarming.client.LeavesColors.leavesColors(LeavesColors.java:18)
	at net.minecraftforge.eventbus.ASMEventHandler_1397_LeavesColors_leavesColors_Block.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$9676/1059143319.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$468/2103877926.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 837600664 bytes (798 MB) / 3062890496 bytes (2921 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m -XX:PermSize=256m
	
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
Mod List: 
		UnionLib-1.15.2-1.2.3.jar UnionLib {unionlib@1.2.3 CREATE_REGISTRIES}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 CREATE_REGISTRIES}
		Guidebook-1.15.2-3.0.5.jar Guidebook {gbook@3.0.5 CREATE_REGISTRIES}
		AoV-1.15-0.14.0.jar Angel of Vengeance {aov@1.15-0.14.0 CREATE_REGISTRIES}
		0.0.5c-releasecandidate1.jar NetherBackport {netherbackport@1.0.0 CREATE_REGISTRIES}
		forgiveness-1.15.2-0.0.3.jar Forgiveness {forgivenessmod@0.0.3 CREATE_REGISTRIES}
		vanillaboom-1.15.2-1.6.5.1-universal.jar Vanilla Boom {vanillaboom@1.6.5.1 CREATE_REGISTRIES}
		mcws-win-1.15.2-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 CREATE_REGISTRIES}
		Guide-API-VP-1.15.2-2.2.0.jar Guide-API VP {guideapi-vp@2.2.0 CREATE_REGISTRIES}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 CREATE_REGISTRIES}
		sakura_forest_1.0.0.jar Sakura Forest {sakura_forest@1.0.0 CREATE_REGISTRIES}
		CTM-MC1.15.2-1.1.1.13.jar ConnectedTexturesMod {ctm@MC1.15.2-1.1.1.13 CREATE_REGISTRIES}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 CREATE_REGISTRIES}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 CREATE_REGISTRIES}
		Vanilla-Crafts-and-Expansion-20200625c.jar Vanilla Crafts & Expansion {vanillaexpansion@20200625c CREATE_REGISTRIES}
		potionofbees-1.15.2-1.0.1.jar Potion of Bees {potionofbees@1.15.2-1.0.1 CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 CREATE_REGISTRIES}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.2.4.jar Apotheosis {apotheosis@3.2.4 CREATE_REGISTRIES}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 CREATE_REGISTRIES}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 CREATE_REGISTRIES}
		TMechworks-1.15.2-2.2.0.jar Tinkers' Mechworks {tmechworks@2.2.0 CREATE_REGISTRIES}
		shetiphiancore-1.15-3.7.4.jar ShetiPhian-Core {shetiphiancore@3.7.4 CREATE_REGISTRIES}
		structure-gel-api-1.15.2-1.1.0.jar Structure Gel API {structure_gel@1.1.0 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 CREATE_REGISTRIES}
		entangled-1.2.5-mc1.15.jar Entangled {entangled@1.2.5 CREATE_REGISTRIES}
		GreaterEye-1.15.2-1.0.14.jar GreaterEye {greater_eye@1.0.11 CREATE_REGISTRIES}
		MoreBows-1.15.2-1.4.0.jar MoreBows {morebows@1.4.0 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 CREATE_REGISTRIES}
		projectvibrantjourneys-1.15.2-2.0.3.jar Project: Vibrant Journeys {projectvibrantjourneys@1.15.2-2.0.3 CREATE_REGISTRIES}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a CREATE_REGISTRIES}
		astral-1.6.6.jar Astral {astral@1.6.6 ERROR}
		simplefarming-1.15.2-1.3.0.jar Simple Farming {simplefarming@1.15.1-1.3.0 CREATE_REGISTRIES}
		randomenchants-3.1.1.jar Random Enchants {randomenchants@3.1.1 CREATE_REGISTRIES}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 CREATE_REGISTRIES}
		tetra-1.15.2-2.18.1.jar Tetra {tetra@1.15.2-2.18.1 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 CREATE_REGISTRIES}
		flying_things-1.8.9-1.15.2.jar The Flying Things {flying_things@1.8.9 CREATE_REGISTRIES}
		corail_woodcutter-1.1.3-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.3 CREATE_REGISTRIES}
		RealityMod-1.1.jar Reality Mod {realitymod@1.0 CREATE_REGISTRIES}
		extlights-2.1.jar Extended Lights {extlights@2.1 CREATE_REGISTRIES}
		Sullys-Mod--v0.7--1.15.2--forge.jar Sully's Mod {sullys_mod@V0.8 CREATE_REGISTRIES}
		EndReborn [0.6.1].jar End: Reborn {endreborn@0.6.1 CREATE_REGISTRIES}
		additionalevents-1.1.jar Additional Events {additionalevents@1.1 CREATE_REGISTRIES}
		GokiStats-1.15.2-1.2.10.jar Goki Stats {gokistats@1.2.10 CREATE_REGISTRIES}
		xercapaint-1.15.2-2.1.jar Joy of Painting {xercapaint@1.15.2-2.1 CREATE_REGISTRIES}
		Gobber2-1.15.2-2.2.102.jar Gobber 2 {gobber2@2.2.99 CREATE_REGISTRIES}
		EnigmaticLegacy-1.7.2.jar Enigmatic Legacy {enigmaticlegacy@1.7.2 CREATE_REGISTRIES}
		buildersaddition-20200617b.jar Builders Crafts & Addition {buildersaddition@20200617b CREATE_REGISTRIES}
		TheAbyss 3.0.0gm 1.15.2.jar TheAbyss {theabyss@3.0.0b1 CREATE_REGISTRIES}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 CREATE_REGISTRIES}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 CREATE_REGISTRIES}
		 skeleton-expansion-3.0.1_1.15.2.jar Skeleton Expansion+ {skeleton_expansion@1.0.0 CREATE_REGISTRIES}
		SakuraRosea-1.5.4-MC1.15.2.jar Sakura Rosea {sakurarosea@1.5.4 CREATE_REGISTRIES}
		the_bumblezone-1.15.2-1.3.10.jar The Bumblezone {the_bumblezone@1.15.2-1.3.10 CREATE_REGISTRIES}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 CREATE_REGISTRIES}
		exoticbirds-1.15.2-1.0.2.jar Exotic Birds {exoticbirds@1.0.2 CREATE_REGISTRIES}
		BetterMineshaftsForge-1.15.2-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.6.1.jar Cyclic {cyclic@1.15.2-0.6.1 CREATE_REGISTRIES}
		SaveMyStronghold-1.15.2-1.0.1.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.1 CREATE_REGISTRIES}
		allomancy-4.0.3.jar Allomancy {allomancy@4.0.3 CREATE_REGISTRIES}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 CREATE_REGISTRIES}
		bagofyurting-1.0.0.1.jar Bag of Yurting {bagofyurting@1.0.0.1 CREATE_REGISTRIES}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 CREATE_REGISTRIES}
		Druidcraft-1.15-0.4.31.jar Druidcraft {druidcraft@0.4.31 CREATE_REGISTRIES}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 CREATE_REGISTRIES}
		Bamboo-Blocks-1.15.2-1.4.1.jar Bamboo Blocks {bambooblocks@NONE CREATE_REGISTRIES}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 CREATE_REGISTRIES}
		caelus-FORGE-1.15.2-2.0-beta3.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta3 CREATE_REGISTRIES}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 CREATE_REGISTRIES}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 CREATE_REGISTRIES}
		TravelersBackpack-1.15.2-4.0.6.jar Traveler's Backpack {travelersbackpack@4.0.6 CREATE_REGISTRIES}
		FruitTrees-1.15.2-1.5.2.jar Fruit Trees {fruittrees@1.5.2 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.8.2.jar Kiwi {kiwi@2.8.2 CREATE_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.73-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.73 CREATE_REGISTRIES}
		decorative_blocks-1.15.2-1.7.jar Decorative Blocks {decorative_blocks@1.7 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-2.0.2.jar Dungeon Crawl {dungeoncrawl@2.0.2 CREATE_REGISTRIES}
		MagicDoorknob-1.15.2-0.0.6.315.jar Magic Doorknob {magic_doorknob@1.15.2-0.0.6.315 CREATE_REGISTRIES}
		mahoutsukai-1.15.2-v1.21.3.jar Mahou Tsukai {mahoutsukai@1.15.2-v1.21.3 CREATE_REGISTRIES}
		enchantability-8.1.jar Enchantability {enchantability@8.1 CREATE_REGISTRIES}
		potionbundles-1.2.1.jar PotionBundles {potionbundles@NONE CREATE_REGISTRIES}
		infinityworkswithallarrows-1.0.jar Infinity works with all arrows {infinityworkswithallarrows@1.0 CREATE_REGISTRIES}
		immersive-portals-0.24forMc1.15withForge.jar Immersive Portals {immersive_portals@0.24 CREATE_REGISTRIES}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE CREATE_REGISTRIES}
		forge-1.15.2-31.2.9-universal.jar Forge {forge@31.2.9 CREATE_REGISTRIES}
		More Mobs 1.15.2.jar More Mobs {moremobs@1.0.0 CREATE_REGISTRIES}
		scuba-gear-1.15.2-1.0.1.jar Scuba Gear {scuba_gear@1.0.1 CREATE_REGISTRIES}
		Explorercraft-1.15.2-4.0.2.jar Explorercraft {explorercraft@1.15.2-4.0.2 CREATE_REGISTRIES}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
		UselessSword-1.15.2-V1.2.3.jar Useless Sword {useless_sword@1.2.3 CREATE_REGISTRIES}
		RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 CREATE_REGISTRIES}
		forge-1.15.2-31.2.9-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b CREATE_REGISTRIES}
		ensorcellation-1.15.2-0.4.1b.jar Ensorcellation {ensorcellation@0.4.1b CREATE_REGISTRIES}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.15.2-2.0.9.jar EnchantmentDescriptions {enchdesc@2.0.9 CREATE_REGISTRIES}
		pandoras_creatures-1.15.2-1.0.0.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.0 CREATE_REGISTRIES}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 CREATE_REGISTRIES}
		C.O.M.B.A.T-1.15.2-4.9.4.jar C.O.M.B.A.T {combat@4.9.3 CREATE_REGISTRIES}
		wards-1.15.2-1.4.0.jar Wards {wards@1.15.2-1.4.0 CREATE_REGISTRIES}
		OverpowderedPickles-1.15.2-1.0.7.jar OverpoweredPickles {overpowered_pickles@1.0.4 CREATE_REGISTRIES}
		forbidden_arcanus-1.15.2-1.5.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.5 CREATE_REGISTRIES}
		astikorcarts-1.15.2-1.0.4.jar AstikorCarts {astikorcarts@1.0.4 CREATE_REGISTRIES}
		Atmospheric-1.15.2-1.4.1.jar Atmospheric {atmospheric@1.4.1 CREATE_REGISTRIES}
		Simple-Sorcery-1.15.2-1.1.jar Simple Sorcery {simple_sorcery@1.1.0 CREATE_REGISTRIES}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 CREATE_REGISTRIES}
		Mantle-1.15.2-1.5.15.jar Mantle {mantle@1.5.15 CREATE_REGISTRIES}
		Inspirations-1.15.2-1.1.0.jar Inspirations {inspirations@1.15.2-1.1.0 CREATE_REGISTRIES}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 CREATE_REGISTRIES}
		moarboats-ironchests-plugin-1.15.2-1.0.0.jar Moar Boats Iron-Chests integration {moarboats_ironchests_integration@1.15.2-1.0.0 CREATE_REGISTRIES}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 CREATE_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 CREATE_REGISTRIES}
		AkashicTome-1.3-13.jar Akashic Tome {akashictome@1.3-13 CREATE_REGISTRIES}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 CREATE_REGISTRIES}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 CREATE_REGISTRIES}
		Charmonium-1.15.2-1.0.1.jar Charmonium {charmonium@1.15.2-1.0.1 CREATE_REGISTRIES}
		Covalent-1.15.2-1.0.2.jar Covalent {covalent@1.15.2-1.0.2 CREATE_REGISTRIES}
		extragolems-10.2.1.jar Extra Golems {golems@10.2.1 CREATE_REGISTRIES}
		[1.15.2] SecurityCraft v1.8.19.1.jar SecurityCraft {securitycraft@v1.8.19.1 CREATE_REGISTRIES}
		enderchests-1.15-1.6.2.jar EnderChests {enderchests@1.6.2 CREATE_REGISTRIES}
		DoubleSlabs-1.15-2.10.1.jar Double Slabs {doubleslabs@2.10.1 CREATE_REGISTRIES}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 CREATE_REGISTRIES}
		polyores-2.0.jar Poly's Ores {polyores@2.0 CREATE_REGISTRIES}
		simplytea-1.15.2-2.2.1.jar Simply Tea {simplytea@1.15.2-2.2.1 CREATE_REGISTRIES}
		MoreCrashInfo-1.0.4.jar MoreCrashInfo {morecrashinfo@1.0.4 CREATE_REGISTRIES}
		moarboats-1.15.2-7.0.0.1.jar Moar Boats {moarboats@1.15.2-7.0.0.1 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 CREATE_REGISTRIES}
		connectedglass-1.0.6-mc1.15.jar Connected Glass {connectedglass@1.0.6 CREATE_REGISTRIES}
		occultism-0.2.11.jar Occultism {occultism@0.2.11 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.16.jar Aquaculture 2 {aquaculture@1.15.2-2.0.16 CREATE_REGISTRIES}
		Void_Alchemy-1.15.2-0.9.13.jar Zorum Tweaks Revamped {void_alchemy@1.15.2-0.8 CREATE_REGISTRIES}
		MagicMirror-1.15.2-0.2.4.389.jar Magic Mirror {magic_mirror@1.15.2-0.2.4.389 CREATE_REGISTRIES}
		EnderMail-1.15.2-1.1.3.jar Ender Mail {endermail@1.15.2-1.1.3 CREATE_REGISTRIES}
		Mubble-3.1.1-(Forge-1.15.2).jar Mubble {mubble@3.1.1 CREATE_REGISTRIES}
		farlanders-1.15.2-1.3.1.jar The Farlanders {farlanders@1.3.1 CREATE_REGISTRIES}
		ageoftitans-1.2.0.jar Age of Titans {ageoftitans@1.1.1 CREATE_REGISTRIES}
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)

	FML: 31.2
	Forge: net.minecraftforge:31.2.9
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
        Launched Version: forge-31.2.9
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

```

There was a similar error with some of the other mods, which when I back-tracked the version, they worked fine.

**Comment by Divineaspect** [comment]
use a pastebin to manage logs etc

**Comment by drizzs** [comment]
This issue is not with astral its with a mod called simplefarming

**Comment by exyleknight** [comment]
Alright, thanks, must be colliding with the other ones too then.

**Comment by drizzs** [comment]
Its possible that astral is erroring if you dont have all the mods that it has compatibility with. The only way we can solve that is if you show us the whole log, ideally in a pastebin

**Comment by exyleknight** [comment]
Where would I find the full log? I usually just look at the crash report.

**Comment by drizzs** [comment]
I don't have any packs installed right now i recently reinstalled my OS on this PC, I'm pretty sure in your pack folder there should be a log folder with a "latest" file at the bottom

**Comment by exyleknight** [comment]
https://pastebin.com/m1wd2EHt

**Comment by drizzs** [comment]
It could be that your version of forge is not high enough you should update forge to a higher version, astral is on  31.2.36 and you are on 31.2.9, it looks like the method for this version of astral doesn't exist.

**Comment by exyleknight** [comment]
Alright, I'm using the twitch launcher, so I'll have to update forge manually real quick, then I'll come back and give results

**Comment by drizzs** [comment]
Thank you! The log with the updated version of forge will at least rule out any issues with the method not existing at all!

**Comment by exyleknight** [comment]
It now works, I just checked, and it seems that the launcher for the pack stopped listing the newer versions of forge, which explain why  everything is getting outdated.

Thanks for the help.
