### ISSUE TITLE
Crashing in Inner Realm

### ISSUE THREAD

**Issue by Mysteriaa** [MinerArcana/Astral#108]
I keep crashing upon interacting with the lock blocks in the Inner Realm to return to the Overworld. I am using the latest release (1.6.8.) for Minecraft 1.15.2. Using a command to manually return to the Overworld did not result in a crash.

Crashlog: https://paste.ee/p/kosPJ (Actual crashlog is viewed on line #10654)

**Comment by drizzs** [comment]
Hi there, I was going over your crash log It seems the issue happens in reference to another mod, Whats happening is that you have a mod called ComfyCozy, This mod has an event which happens when Potions expire, in this event he searches for a hand which results in a null exception. I suggest you check with ComfyCozy to make sure the hand doesn't return null. 


[m[1;31m[23:26:40] [Render thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Invalid hand null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class bee.beeshroom.comfycozy.events.FortuneExpirirationEvent FortuneExpired(Lnet/minecraftforge/event/entity/living/PotionEvent$PotionRemoveEvent;)V
		2: ASM: class com.alan19.astral.events.astraltravel.StartAndEndHandling astralTravelRemove(Lnet/minecraftforge/event/entity/living/PotionEvent$PotionRemoveEvent;)V
		3: ASM: PulseManager[inspirations] propagateEvent(Lnet/minecraftforge/eventbus/api/Event;)V
java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.entity.LivingEntity.func_184586_b(LivingEntity.java:1623)
->	at bee.beeshroom.comfycozy.events.FortuneExpirirationEvent.FortuneExpired(FortuneExpirirationEvent.java:55)

**Comment by Mysteriaa** [comment]
I'll let the author know about this issue, thank you!

**Comment by Alan19** [comment]
Any updates on the issue?
