### ISSUE TITLE
[1.15.2 - 1.2.11] Going astral in a biome with custom grass colors causes crash

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinerArcana/Astral#67]
I was using the latest Astral version with a mod called World Blender which imports other mod's features and structures into its dimension. When i tried going astral in this dimension, I get this crash:
```
java.lang.IllegalArgumentException: Color parameter outside of expected range: Green
	at java.awt.Color.testColorValueRange(Color.java:310) ~[?:1.8.0_51] {}
	at java.awt.Color.<init>(Color.java:395) ~[?:1.8.0_51] {}
	at java.awt.Color.<init>(Color.java:369) ~[?:1.8.0_51] {}
	at com.alan199921.astral.blocks.BlockRenderHandler.addEtherealTint(BlockRenderHandler.java:75) ~[?:1.2.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.alan199921.astral.blocks.BlockRenderHandler.lambda$registerBiomeBasedBlockColors$0(BlockRenderHandler.java:50) ~[?:1.2.11] {re:classloading,pl:runtimedistcleaner:A}
	at com.alan199921.astral.blocks.BlockRenderHandler$$Lambda$2950/788871227.getColor(Unknown Source) ~[?:?] {}
```

Full crashlog here: https://hatebin.com/jizvwuarpn

It seem this method is causing the crash when an rgb value goes beyond 255 or below 0 as World Blender has a biome with extremely green grass color. Adding some Math.min and Math.max in to limit the range in rgb should solve this issue.
https://github.com/MinerArcana/Astral/blob/02bb0960395b72b4d311ee522de194bd2a0c8816/src/main/java/com/alan199921/astral/blocks/BlockRenderHandler.java#L70-L76

**Comment by Alan19** [comment]
Try this build (once it's approved)
https://www.curseforge.com/minecraft/mc-mods/ma-astral/files/2952924

**Comment by Alan19** [comment]
I'm planning to replace the current textures with custom textures in the future, without any tinting.

**Comment by TelepathicGrunt** [comment]
Yep! That resolved the problem!
